Feature/copyright
calm1205/golf_academy pull request #16
Opened 2023-04-14 13:15 UTC by satohiro213

Close #6

## 概要
footer下のcopyrightの作成
## やったこと
>copyright.phpの作成
>ブラウザでの確認のためfooter.phpを一時的にコメント
## やらなかったこと

## 備考

2023-04-14 13:18 UTC, satohiro213 commented
@calm1205 確認お願いします。Git hubへの同期の仕方やブランチの切り出し等に関して間違っていたら教えて欲しいです。

2023-04-15 07:58 UTC, calm1205 reviewed
@satohiro213 
レビューしました。

今後デザイン実装したらpull requestの内容に実装した場所の画像貼っておいて！

今後もコメントにラベルつけていくからラベルって何？てなったら見ておいて。
参考: https://tech.excite.co.jp/entry/2021/04/26/174722

2023-04-15 07:58 UTC, calm1205 commented on .DS_Store
[must]
[.gitignore](https://github.com/calm1205/golf_academy/blob/main/.gitignore)に`.DS_Store`追記頼む。

理由としては、`.DS_Store`はMacOS特有のファイルでソースコードとして管理する不要だから。

参考: https://ios-docs.dev/ds_store/

2023-04-15 08:00 UTC, calm1205 commented on src/index.php
> +
[should]
`footer.php`の中で`include`の方がいい。
なぜならcopyrightはfooterを構成する一部だから。

2023-04-15 08:00 UTC, calm1205 commented on src/components/footer/copyright.php
> +</footer>
👍

2023-04-15 08:00 UTC, calm1205 requested changes
コメントしました！

2023-04-15 08:20 UTC, satohiro213 commented on .DS_Store
追記しました。

2023-04-15 08:30 UTC, satohiro213 commented on src/index.php
> +
訂正しました。

2023-04-15 10:06 UTC, calm1205 approved these changes
@satohiro213 
LGTM！

2023-04-15 10:06 UTC, merged